QC_WS_PATH: /ws
QC_WS_PORT: 8080
QC_WS_TIMEOUT: 5000000000
QC_WS_READ_BUFFER_SIZE: 4096
QC_WS_WRITE_BUFFER_SIZE: 4096
QC_WS_TOPICS:
  - "notifications"
  - "payments"
QC_WS_DB_HOST: localhost
QC_WS_DB_PORT: 6379
QC_WS_DB_USER: test
QC_WS_DB_PASS: queue_cast_manager
